### ISSUE TITLE
vp_token.rs anoma/namada

### ISSUE THREAD

**Issue by cryptomolot** [anoma/namada-docs#122]
in documentation https://docs.namada.net/users/transparent-accounts/send-and-receive-nam-tokens the link to vp_token (Token Validity Predicate) in namada doesn't work, I also couldn't find vp_token.rs in whole Namada repositories but this file exists in anoma/wasm/wasm_source/src ; maybe need to relocate or dublicate

**Comment by bengtlofgren** [comment]
Fixed #151
