### ISSUE TITLE
Base directory folder isn't available on namada docs

### ISSUE THREAD

**Issue by cryptomolot** [anoma/namada-docs#147]
https://docs.namada.net/operators/ibc  if you try to move to "Base directory" - you can't access it.

I think that's what supposed to be there: packages/docs/pages/operators/ledger/base-directory.mdx

**Comment by cryptomolot** [comment]
@bengtlofgren

**Comment by bengtlofgren** [comment]
Great catch!

**Comment by bengtlofgren** [comment]
Fixed in #151
