### ISSUE TITLE
Feedback for “Constructing transfers”

### ISSUE THREAD

**Issue by ekkis** [anoma/namada-docs#290]
how does the transparent address passed to `.signing_keys()` relate to the `source`? I've created a shielded keypair and find no way to produce a public key for it i.e. I find no command in the CLI to show me the public key for a shielded keypair.  does it mean that shielded keypair cannot sign their own transactions?

**Comment by bengtlofgren** [comment]
Yes and no. Long story short, when we talk about signing, we usually talk about signing the inner and wrapper protocol transactions. When a shielded transfer is made, the spending key is used in the construction of the note (zero knowledge proof). However, I believe that it is not used for signing (they are not signing keys). A transparent key is needed for this.
