### ISSUE TITLE
Feedback for “State Sync”

### ISSUE THREAD

**Issue by Rigorously** [anoma/namada-docs#399]
> If an operator trusts the chain past a certain block height, they can fetch snapshots from peers (if they are configured to provide snapshots) and then only replay the chain from this snapshot onward. 

"past a certain block height" should be corrected to "before a certain block height".

The original phrase "past a certain block height" implies that the operator trusts the chain after that block height, whereas the context suggests that they trust the chain up to that point.

**Comment by iskay** [comment]
closed by #410
