### ISSUE TITLE
Add tx expiration details to multisig docs

### ISSUE THREAD

**Issue by gavinly** [anoma/namada-docs#407]
i just discovered that there's a default expiration period for multisig transactions. there's also a flag to designate a period or to set it to never expire. could it be worth noting somewhere that Namada has transaction expiration periods instead of nonce?
https://github.com/anoma/namada-docs/blob/master/packages/docs/pages/users/transparent-accounts/multisignature.mdx

**Comment by iskay** [comment]
closed by #410
