### ISSUE TITLE
General specs cleanup for consistency and completeness

### ISSUE THREAD

**Issue by cwgoes** [anoma/namada-docs#69]
The specs still need a lot of cleanup in order to be readable as a clear standalone document. In particular:
- the language was clearly written by different people and often differs in tone, tense, and style; it should be standardised
- subsections differ in levels of abstraction - some are high-level and others contain lots of implementation details
- some old names persist (e.g. "burn & mint")
- specification should be reviewed alongside code to check for correspondence

**Comment by cwgoes** [comment]
Notes/questions from readthrough:
- Governance, multitoken, and multisignature (established accounts) should probably just get their own sections.
- Are we still using the block space allocator?
- MASP section
    - Include an abstract definition from the cryptographic spec
    - Clearly describe validity predicate correctness conditions
    - Combine burn & mint / convert circuit sections
    - Move trusted setup docs somewhere else (and link to them)
- Ethereum bridge
    - Appears to be a lot of duplication between the top-level section and the sub-section content
- IBC
    - Should define IBC validity predicate correctness conditions
- Proof-of-stake
    - Section content needs to be updated
- Shielded pool incentives
    - Should define MASP incentives validity predicate correctness conditions

**Comment by sug0** [comment]
* Ethereum bridge
    * https://github.com/anoma/namada-docs/issues/85
* Block space allocator
    * We are still using it, but its specs are outdated, as they do not mention gas fees, and the order of allocation is wrong (we now allocate encrypted, then decrypted and finally protocol txs, in this order)

**Comment by cwgoes** [comment]
Closing in favor of https://github.com/anoma/namada-docs/issues/277.
