### ISSUE TITLE
The picture in "Experimenting" -> "Spinning up a local network" section is not readable

### ISSUE THREAD

**Issue by karbyshev** [anoma/namada-docs#72]
The picture on https://docs.namada.net/experimental/local-network page is not readable (on the laptop screen).

**Comment by bengtlofgren** [comment]
I agree. Ideally we have some way to "zoom" into an image or view it full screen in the docs. @pedrorezende do you know any way of doing this with Nextra/CSS magic? Otherwise I'll look into it

**Comment by pedrorezende** [comment]
Hi all. I've just opened the PR #74 containing a solution and a few tweaks for this specific case
